### ISSUE TITLE
Upgrade XNAT version to 1.8.0.1

### ISSUE THREAD

**Issue by exxa-tech** [Australian-Imaging-Service/xnat-build#2]
More of a suggestion than an issue.

**Comment by dean-taylor** [comment]
Currently having incompatibility issues with some AIS supported plugins. Includes the openid auth provider plugin.
A release candidate image has been added to help with ongoing development.

**Comment by dean-taylor** [comment]
Work in coordination with Alastair has completed a viable 1.8.2 xnat image
