### ISSUE TITLE
Update to xnat 1.8.4.1

### ISSUE THREAD

**Issue by exxa-tech** [Australian-Imaging-Service/xnat-build#28]
This supersedes this issue:
https://github.com/Australian-Imaging-Service/xnat-build/issues/27

XNAT 1.8.4.1 fixes some issues with 1.8.4.

This new version solves some issues that have plagued the AIS 1.8.3 rollout, specifically with the OpenID plugin.
On top of this Mark has worked with XNAT upstream team and will shortly release an OpenID plugin so the deployment update should ensure both the XNAT version and OpenID plugin update are done at the same time.
XNAT 1.8.4 release notes:
https://wiki.xnat.org/news/blog/2022/02/xnat-1-8-4-released

XNAT 1.8.4.1 hotfix notes:
https://wiki.xnat.org/news/blog/2022/03/xnat-1-8-4-1-hotfix-release

**Comment by fxusyd** [comment]
XNAT is updated to v1.8.4.1. Standard plugins are also updated. (commit 835d91e2e3a097041546c1a18fd1b64cc57637a8)
