### ISSUE TITLE
Add OHIF Viewer Plugin to  XNAT Build for 1.8.2

### ISSUE THREAD

**Issue by exxa-tech** [Australian-Imaging-Service/xnat-build#5]
With the release of XNAT 1.8.2 the original image viewer is no longer included with the package. Therefore you can't actually view any images (apart from snapshots) in XNAT. Some may say that is important!

Suggested code to fix. Please bear in mind I haven't used Packer before so will need validation.

```
xnat_version = 1.8.2
xnat_ver_17 = 1.7.6
plugin_container_service_ver = 3.0.0
plugin_ldap_auth_ver = 1.1.0
plugin_openid_auth_ver = 1.0.2
plugin_ohif-viewer_ver = 3.0.1

xnat_war = xnat-web-$(xnat_version).war
xnat_url = https://bitbucket.org/xnatdev/xnat-web/downloads/$(xnat_war)
xnat_war_17 = xnat-web-$(xnat_ver_17).war
xnat_url_17 = https://bitbucket.org/xnatdev/xnat-web/downloads/$(xnat_war_17)
plugin_container_service_jar = container-service-$(plugin_container_service_ver)-fat.jar
plugin_container_service_url = https://bitbucket.org/xnatdev/container-service/downloads/container-service-$(plugin_container_service_ver)-fat.jar
plugin_ldap_auth_jar = ldap-auth-plugin-$(plugin_ldap_auth_ver).jar
plugin_ldap_auth_url = https://bitbucket.org/xnatx/ldap-auth-plugin/downloads/ldap-auth-plugin-1.1.0.jar
plugin_openid_auth_jar = openid-auth-plugin-$(plugin_openid_auth_ver).jar
plugin_openid_auth_url = https://github.com/Australian-Imaging-Service/xnat-openid-auth-plugin/releases/download/$(plugin_openid_auth_ver)/xnat-openid-auth-plugin-all-$(plugin_openid_auth_ver).jar
#plugin_openid_auth_url = http://dev.redboxresearchdata.com.au/nexus/service/local/repositories/snapshots/content/au/edu/qcif/xnat/openid/openid-auth-plugin/$(plugin_openid_auth_ver)-SNAPSHOT/openid-auth-plugin-$(plugin_openid_auth_ver)-20190409.122010-10.jar
plugin_ohif-viewer_jar = ohif-viewer-$(plugin_ohif-viewer_ver)-XNAT-1.8.0.jar
plugin_ohif-viewer_url = https://bitbucket.org/icrimaginginformatics/ohif-viewer-xnat-plugin/downloads/ohif-viewer-$(plugin_ohif-viewer_ver)-XNAT-1.8.0.jar

plugins_17 = $(plugin_container_service_jar) $(plugin_ldap_auth_jar) $(plugin_openid_auth_jar)
plugins = $(plugin_container_service_jar) $(plugin_ldap_auth_jar) $(plugin_openid_auth_jar) $(plugin_ohif-viewer_jar)

all : $(xnat_war) $(xnat_war_17)

$(xnat_war) : $(plugins)
        wget --no-verbose -O $(xnat_war) $(xnat_url)

$(xnat_war_17) : $(plugins_17)
        wget --no-verbose -O $(xnat_war_17) $(xnat_url_17)

$(plugin_container_service_jar) :
        wget --no-verbose -O $(plugin_container_service_jar) $(plugin_container_service_url)

$(plugin_ldap_auth_jar) :
        wget --no-verbose -O $(plugin_ldap_auth_jar) $(plugin_ldap_auth_url)

$(plugin_openid_auth_jar) :
        wget --no-verbose -O $(plugin_openid_auth_jar) $(plugin_openid_auth_url)

$(plugin_ohif-viewer_jar) :
        wget --no-verbose -O $(plugin_ohif-viewer_jar) $(plugin_ohif-viewer_url)

.PHONY : clean
clean :
        rm -f $(xnat_war)
        rm -f $(xnat_war_17)
        rm -f $(plugins)
        rm -f $(plugins_17)
```

**Comment by exxa-tech** [comment]
You mentioned that standard procedure would be to create your own image based on the XNAT-Build one and add plugins / customise it to your requirements.
So I created my own Packer container and then added the plugins I wanted and pushed it to DockerHub.
I then updated the values file to pull the image from my dockerhub repo in my Helm chart and redeployed.
I also added an image to the /usr/loca/tomcat/webapps/ROOT/images directory - mq.png. 
I can confirm that this image is there when I exec into the pod but the plugins are not when deploying - only openid. They are there when I exec into the container on my computer. But you already knew that. I seem to recall you said that you had some convoluted mechanism to deploy the plugins requiring a properties file.
This would seemingly be pulled from secrets.yaml and refer only to openid.
I, and everyone who ever wants to use XNAT 1.8.2 will need to install OHIF viewer 3.0.1 if they want to view images (and if they don't there isn't ***much*** point in XNAT), so how do they / we do this?

**Comment by exxa-tech** [comment]
OK never mind - I got OHIF viewer working.
1. In the Xnat-build repo - update the Makefile as above.
2. Again in the Xnat-build repo update the following lines in xnat-web.pkr.hcl:  

```
variable "xnat_plugins_list" {
  default = [
    "container-service-3.0.0-fat.jar",
    "ldap-auth-plugin-1.1.0.jar",
    "openid-auth-plugin-1.0.2.jar",
    "ohif-viewer-3.0.1-XNAT-1.8.0.jar"
  ]
  type = list(string)
}
```

3. Add the following line to your Helm values chart under plugins:  

```
 plugins:
    ohif-viewer: {}
```

Can confirm this works in my install xnat.exxa.tech. Containers also enabled now.

**Comment by dean-taylor** [comment]
Two minor version branches have been created allowing for the addition of variations between v1.7 and v1.8. The viewer has been added to v1.8 branch.
